version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: poetry run python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

